### ISSUE TITLE
Failed on nitialise AWX files and environement

### ISSUE THREAD

**Issue by VNMan148** [SckyzO/awx-ha-cluster#1]
So I have 3 servers setup with one postgres server already in use with old version of awx.
These servers do not have access to internet, I have manually install docker-ce on the 3 servers.

these are errors I have when run Initialise.

TASK [base : Install YUM dependencies] *********************************************************************************************************************************************************************
fatal: [awx02]: FAILED! => {"changed": false, "msg": "The Python 2 bindings for rpm are needed for this module. If you require Python 3 support use the `dnf` Ansible module instead.. The Python 2 yum module is needed for this module. If you require Python 3 support use the `dnf` Ansible module instead."}
fatal: [awx01]: FAILED! => {"changed": false, "msg": "The Python 2 bindings for rpm are needed for this module. If you require Python 3 support use the `dnf` Ansible module instead.. The Python 2 yum module is needed for this module. If you require Python 3 support use the `dnf` Ansible module instead."}

**Comment by SckyzO** [comment]
Hi VNMan. I think just comment in your inventory this line : ansible_python_interpreter=/usr/bin/python3

Tell me if it's work.

**Comment by VNMan148** [comment]
I just removed dock-ce repo definitions from the play book. I installed dock-ce manually.

**Comment by SckyzO** [comment]
What version of CentOS are you using?

**Comment by SckyzO** [comment]
Update is coming for install or not docker
